kind: pipeline
type: docker
name: base_codec

steps:
- name: build
  image: ubuntu:groovy
  commands:
    - apt-get -y -q update --fix-missing
    - apt-get -y -q upgrade
    - apt-get -y -q install build-essential cmake catch2
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBASE_CODEC_ENABLE_TESTS=ON
    - make -j4
    - ctest

  trigger:
    branch:
    - master
